# .github/workflows/deploy.yml
name: Build & Deploy .NET Framework 4.8 App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      # 1) Check out the repo
      - uses: actions/checkout@v4

      # 2) Ensure msbuild.exe is on PATH
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # 3) Restore NuGet packages and build the project
      - name: Restore & Build
        shell: cmd
        run: |
          REM Restore NuGet packages for project
          msbuild MathCaptchaBatchDownloader\MathCaptchaBatch.csproj /t:Restore /p:Configuration=Release
          REM Build project
          msbuild MathCaptchaBatchDownloader\MathCaptchaBatch.csproj /t:Build /p:Configuration=Release

      # 4) Publish to a folder for GitHub Pages
      - name: Publish to filesystem
        shell: cmd
        run: |
          REM Publish web app to 'publish' directory
          msbuild MathCaptchaBatchDownloader\MathCaptchaBatch.csproj ^
            /p:Configuration=Release ^
            /p:DeployOnBuild=true ^
            /p:WebPublishMethod=FileSystem ^
            /p:PublishUrl="%CD%\publish"

      # 5) Upload the 'publish' folder as a Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: publish

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 6) Fetch the Pages artifact
      - uses: actions/download-pages-artifact@v1

      # 7) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
