# .github/workflows/deploy.yml
name: Build & Deploy ASP.NET MVC (net48) to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore & Build with MSBuild
        shell: cmd
        run: |
          msbuild MathCaptchaBatch.csproj /t:Restore /p:Configuration=Release
          msbuild MathCaptchaBatch.csproj /p:Configuration=Release

      - name: Publish to filesystem
        shell: cmd
        run: |
          msbuild MathCaptchaBatch.csproj ^
            /p:Configuration=Release ^
            /p:DeployOnBuild=true ^
            /p:WebPublishMethod=FileSystem ^
            /p:PublishUrl="%CD%\publish"
          type nul > publish\.nojekyll

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: publish

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
