name: Build and deploy ASP app to Azure Web App - my-captcha-downloader

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore MathCaptchaBatchDownloader.csproj

      - name: Build project
        run: msbuild "MathCaptchaBatchDownloader.csproj" /nologo /verbosity:minimal /p:Configuration=Release

      - name: Assemble published site
        shell: pwsh
        run: |
          # create output dirs
          New-Item -ItemType Directory -Force -Path published,published\bin,published\Views | Out-Null

          # copy the compiled DLL
          Copy-Item -Path "bin\Release\MathCaptchaBatchDownloader.dll" `
                    -Destination published\bin\ -Force

          # copy Views
          Copy-Item -Path "Views\*" `
                    -Destination published\Views\ -Recurse -Force

          # copy Content if present
          if (Test-Path "Content") {
            Copy-Item -Path "Content\*" `
                      -Destination published\Content\ -Recurse -Force
          }

          # copy Scripts if present
          if (Test-Path "Scripts") {
            Copy-Item -Path "Scripts\*" `
                      -Destination published\Scripts\ -Recurse -Force
          }

          # copy config and Global.asax
          Copy-Item -Path "Web.config" published\ -Force
          Copy-Item -Path "Global.asax" published\ -Force

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: published/**

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'my-captcha-downloader'
          slot-name: 'Production'
          package: published
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7174F4F018AD442D85E55EC0D16A6233 }}
