# .github/workflows/azure-deploy.yml

name: Build and deploy ASP.NET MVC5 to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore MathCaptchaBatchDownloader.csproj

      - name: Build project
        run: msbuild MathCaptchaBatchDownloader.csproj /nologo /verbosity:minimal /p:Configuration=Release

      - name: Assemble published site
        shell: pwsh
        run: |
          # clean and recreate published/
          Remove-Item -Recurse -Force published -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Force -Path published, published\bin, published\Views | Out-Null

          # copy compiled dll
          Copy-Item -Path "bin\Release\MathCaptchaBatchDownloader.dll" `
                    -Destination published\bin\ -Force

          # copy Razor views
          Copy-Item -Path "Views\*" `
                    -Destination published\Views\ -Recurse -Force

          # copy static assets
          if (Test-Path Content) {
            Copy-Item -Path "Content\*" -Destination published\Content\ -Recurse -Force
          }
          if (Test-Path Scripts) {
            Copy-Item -Path "Scripts\*" -Destination published\Scripts\ -Recurse -Force
          }

          # copy root config files
          Copy-Item -Path "Global.asax","Web.config" -Destination published\ -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: asp-artifact
          path: published/**

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: asp-artifact

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'my-captcha-downloader'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7174F4F018AD442D85E55EC0D16A6233 }}
          package: published
